### ISSUE TITLE
Update and expand scripts for new ROS API

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc_ros_diagnostics#1]
Creating this issue for record keeping purposes.

@mauricefallon mentions in ihmcrobotics/ihmc-open-robotics-software#44 about the need for helpful example scripts. The scripts here used to do that but they need to be updated to show off the new API. Specifically:
1. We must update the scripts to use the new messages,
2. We should add scripts showing off the improved whole-body trajectory functionality
3. We should probably have more than just the box step demo for walking

**Comment by scpeters** [comment]
Perhaps you could also add a `stable/legacy` tag to preserve functionality for users of old code.

**Comment by scpeters** [comment]
I've started updating boxStep.py in https://github.com/scpeters/ihmc_ros_diagnostics/commit/26031f0dd9e1e511ed986f45a0afc365642ab706

I'll wait until there is a `stable/legacy` tag before creating a pull request.

**Comment by dljsjr** [comment]
@scpeters Tag created, thanks for waiting!

**Comment by scpeters** [comment]
Cool, I just made PR #2 to update boxStep.py

**Comment by dljsjr** [comment]
This probably should have been closed a while ago, but it is in fact relevant again. And probably should have been resolved in 0.9.0.

**Comment by dljsjr** [comment]
I'm closing this issue as we will be deprecating this package in favor of some new ones with our next release.
